// v16/sprites/vehicles_b.js — CAT 740 rock truck (empty + loaded), CAT D8 dozer, dirt pile.
// Plain script, no modules. Light from top-left; ink outline on the outer silhouette only; 1px ink ground-shadow row under the wheels/tracks.
// Facing: rock trucks face LEFT (cab on the left; use opts.flip to run them the other way). Dozer faces RIGHT (blade on the right).
// Custom colours in this file (max 6): u #3a3e45 rubber catching light on tires/track.
var SPR16 = window.SPR16 = window.SPR16 || {};

var VEH_B_PAL = {Y:"#ffe466", y:"#f2c400", s:"#c99d00", d:"#8a6a00", T:"#1a1c1e", u:"#3a3e45", h:"#555555", c:"#c8ccd2", C:"#7c8289", D:"#4a4f56", g:"#d8f0ff", G:"#9fd8ff", b:"#5a9ad0", W:"#ffffff", k:"#141018", A:"#ffb000", o:"#ff7a00", p:"#a06a30", l:"#8f5a26", m:"#7a4a1c", M:"#5e3812", n:"#3f2408", R:"#c4c4c4", r:"#9a9a9a", E:"#6f6f6f"};

// ---- rock_truck_empty: CAT 740 articulated rock truck, empty, facing LEFT. Cab with ROPS + beacon + mirror, exhaust stack, hitch, ribbed duck-tail box with lifted rear lip, 3 lugged tires. ----
SPR16.rock_truck_empty = {
  w: 60, h: 36,
  anchor: [0, 36],
  pal: VEH_B_PAL,
  rows: [
    "................kkkk........................................",
    "...............kDDDDk.......................................",
    "................kcCk........................................",
    "................kcCk........................................",
    "................kcCk........................................",
    ".....kk.....kkkkkcCkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..",
    "....kAAk...kYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYyyYk.",
    "....kookkkkkyYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYyysk.",
    "...kYDDYYYYYssssssssyssyyyyyyyYsyyyyyyYsyyyyyyYsyyyyyyyYysk.",
    "..kYyyyyyyyyyyyskkkkyysYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYysk.",
    ".kDYggGsgggggGysk..kyysyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyYysk.",
    ".kcYgGGsgWGGGbysk..kyysYyyyyyyYsyyyyyyYsyyyyyyYsyyyyyyyYysk.",
    ".kDYgGGsgGGGGbysk..kyysYyyyyyyYsyyyyyyYsyyyyyyYsyyyyyssYdsk.",
    "kYYyGGbsGGGGbbyskkkkyysYyyyyyyYsyyyyyyYsyyyyyyYsyyyssssYysk.",
    "kYyyGbbsbbbbbbyskCDDyysYyyyyyyYsyyyyyyYsyyyyyyYsyssssssdddk.",
    "kDCyyyyyssssssyskCDDyysYyyyyyyYsyyyyyyYsyyyyyyYssssssddkkk..",
    "kcDyyyyyyyyyyyyskCDDyysYyyyyyyYsyyyyyyYsyyyyysYssssddkk.....",
    "kDDssssdsssssssskCcDyysYyyyyyyYsyyyyyyYsyyyssssssddkk.......",
    "kcDssssssssssssskCDkyysYyyyyyyYsyyyyyyYsyssssssddkk.........",
    "kssdddddddddddddkCDDyysYyyyyyyYsyyyyyyYsyssssddkkkk.........",
    "kCCCCCCCuuuukukkkCDDyysYsssssuuuukusssYssssdduuuukuk........",
    "kDDDDDDkTTTTTTukkCDDMysssMsMkTTTTTTusMssMddCkTTTTTTuk.......",
    ".kCCDkuTTTTTTTTTkCDDddddddduTTTTTTTTTddddDDuTTTTTTTTTk......",
    "..kkDuTTTTccTTTTkDDMMDDMMDuTTTTccTTTTkDDMDuTTTTccTTTTkk.....",
    ".kmCuTTTcchhhhTTTTDDDDDDMMTMTcchhhhTTTTDDuTMTcchhhhTTTTk....",
    "..kkkMTTchhhhhTMTMDDDDDDDkTTTchhhhhTTTuDDkTTMchhhhhTTTuk....",
    "...kuTTchhcDhhDTTTkkkkkkkMTTchhcDhhDTTMkkuTTchhcDhhDTTTk....",
    "...kuTTchhDDhhDTTTk.....kuTTchhDDhhDTTTkkuTTchhDDhhMTTTk....",
    "...kuTMThhhhhDTTTkk.....kuMTThhhhhDTTTkkkuTTThhhhhDTTTkk....",
    "...kuTTThhhhDDTTTTk.....kuTTThhhhDMMMTMkkuTTThhhhDDTTTTk....",
    "....kkTTTTDDMTTTuk.......kkTTTTDDTTTTuk..kkTTTMDDTTTTuk.....",
    ".....kTTTTTTTTTTk.........kTTTTTTTTTTk....kTTTTMTTTTTk......",
    "......kuMTTTTTkk...........kuTTTTTTkk......kuTTTTTTkk.......",
    ".......kTkTTMTk.............kMkTTuTk........kTkTTuTk........",
    "........kkkkkk...............kkkkkk..........kkkkkk.........",
    ".......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......",
  ],
};

// ---- rock_truck_loaded: Same truck, heaped rock/dirt load (hi/light/base/shade + a few grey rocks). ----
SPR16.rock_truck_loaded = {
  w: 60, h: 36,
  anchor: [0, 36],
  pal: VEH_B_PAL,
  rows: [
    "................kkkk....kkkppkkpppkkkppkkk..................",
    "...............kDDDDk.kkpppllpplllpppllpppkk................",
    "................kcCkkkpplllmmlRrmmlllmmlllppkkk.............",
    "................kcCkpplRrmmmmmrEmmmmmmRmmmllpppkkkk.........",
    "................kcCpllmmEmmnmmmmmmmmmmmrmmmmrlMppppkkkk.....",
    ".....kk.....kkkkkcplmmmmmmmmmmmmmmmnmmmmmmmmmEMMMMrppppkkk..",
    "....kAAk...kYYYYYYnMMMnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnyyYk.",
    "....kookkkkkyYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYyysk.",
    "...kYDDYYYYYssssssssyssyyyyyyyYsyyyyyyYsyyyyyyYsyyyyyyyYysk.",
    "..kYyyyyyyyyyyyskkkkyysYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYysk.",
    ".kDYggGsgggggGysk..kyysyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyYysk.",
    ".kcYgGGsgWGGGbysk..kyysYyyyyyyYsyyyyyyYsyyyyyyYsyyyyyyyYysk.",
    ".kDYgGGsgGGGGbysk..kyysYyyyyyyYsyyyyyyYsyyyyyyYsyyyyyssYdsk.",
    "kYYyGGbsGGGGbbyskkkkyysYyyyyyyYsyyyyyyYsyyyyyyYsyyyssssYysk.",
    "kYyyGbbsbbbbbbyskCDDyysYyyyyyyYsyyyyyyYsyyyyyyYsyssssssdddk.",
    "kDCyyyyyssssssyskCDDyysYyyyyyyYsyyyyyyYsyyyyyyYssssssddkkk..",
    "kcDyyyyyyyyyyyyskCDDyysYyyyyyyYsyyyyyyYsyyyyysYssssddkk.....",
    "kDDssssdsssssssskCcDyysYyyyyyyYsyyyyyyYsyyyssssssddkk.......",
    "kcDssssssssssssskCDkyysYyyyyyyYsyyyyyyYsyssssssddkk.........",
    "kssdddddddddddddkCDDyysYyyyyyyYsyyyyyyYsyssssddkkkk.........",
    "kCCCCCCCuuuukukkkCDDyysYsssssuuuukusssYssssdduuuukuk........",
    "kDDDDDDkTTTTTTukkCDDsysMsssMkTTTTTTuMssssddCkTTTTTTuk.......",
    ".kCCDkuTTTTTTTTTkCMMddddddduTTTTTTTTTddddMDuTTTTTTTTTk......",
    "..kkDuTTTTccTTTTkDDMMDDDMMuTTTTccTTTTkDDMDuTTTTccTTTTkk.....",
    ".kCCuTTTcchhhhTMTTDDDDDDDuTTTcchhhhTTTTMDMTTTcchhhhTTMTk....",
    "..kkkMTTchhhhhMMTuDMDDDDMkTMTchhhhhTTTuDDkTTTchhhhhTTTuk....",
    "...kuTTchhcDhhDMTTkkkkkkkuTTchhcDhhDTTTkkuTTchhcDhhMTTTk....",
    "...kuMTchhDMhhDTTTk.....kuTTchhMDhhDTTTkkuMTchhDDhhDMTTk....",
    "...kuTTThhhhhDTTMkk.....kuTTThhhhhDTTTkkkuTMMhhhhhDTTTkk....",
    "...kMTTThhhhDMMTTTk.....kuTMThhhhDMMMTTkkuTTThhhhDDTTTTk....",
    "....kkMTTTDDTTMMuk.......kkMTTTDDMMTTMk..kkTMTTDDTTTTuk.....",
    ".....kTTTTTTTTTTk.........kTTTTTTMTTTk....kMTTTTTMTMTk......",
    "......kuTTTTTTkk...........kuTTMTTMkk......kuTTTTTTkk.......",
    ".......kTkTTuTk.............kTkTTuTk........kTkTTuMk........",
    "........kkkkkk...............kkkkkk..........kkkkkk.........",
    ".......kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......",
  ],
};

// ---- dozer: CAT D8 facing RIGHT: high-drive track (sprocket up, idler front, 4 rollers), ROPS cab with glass + specular + seat, stack + precleaner, ripper at the rear, curved blade with push arms, tilt cylinder and cutting edge. ----
SPR16.dozer = {
  w: 60, h: 44,
  anchor: [0, 44],
  pal: VEH_B_PAL,
  rows: [
    ".............kkkkkkAokkkkkk.................................",
    "............kYYYYYYYYYYYYYYk................................",
    "...........kYYYYYYYYYYYYYYYYk.kkkk..........................",
    "...........kysggggggsgggggsdkkkDDkk.........................",
    "..........kDysgWgGGGsGGGGGsdk.kcCk..........................",
    "..........kcysgGGGGGsGGGGbsdk.kcCkkkkkk.....................",
    "..........kDysgGGGGGsGGGGbsdk.kcCkDCDDDk....................",
    "...........kysgChhhGsGGGGbsdk.kcCkkCDDk.....................",
    "...........kysghhhhGsGbbbbsdk.kcCkkCDDk.....................",
    "...........kysGDDDDGsGbbbbsdk.kcCkkCDDk.....................",
    "...........kysGDDDDbsbbbbbsdk.kcCkkCDDk.....................",
    "...........kysbDDDDbsbbbbbsdk.kcCkkCDDk.....................",
    ".........kkkddddddddddddddddkkkcCkkCDDkkkkk.................",
    "........kyYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYyk................",
    "........kYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYCDDDk...............",
    "........kYyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyCcCCk...............",
    ".kkk....kYyyyyyyyyyyyyyyyyyyddddddydddddCCCCk...............",
    "kCDDk...kYyyyyyyyyyyyyyyyyyysYssssysssssCCCCck..kkkk........",
    "kCDDkkkkkYyyyyyyyyyyyyyyyyyyssssssyssdssCCCCDckkYYYYkk......",
    "kCDDcccccYdddddddddddddddddyssssssysssssCCCCkDcsYyysyyk.....",
    "kCDDCCCCCsssssssssssssssssssssssssssssssCDDDkkDsYyyskk......",
    "kCkDkkkkkdddddddddddddddddddddddddddddddDDDDk.ksYyysk.......",
    "kCDDk....kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..ksYyysk.......",
    "kCDDk....kTCTTCTTTTkkk........................ksYyysk.......",
    "kCkDkkkkkTTccccTTTuTTTkkk.....................ksYyysk.......",
    "kCDDcccccTchhhhhTTTukuTTTkkk..................kdsYyysk......",
    "kCDDCCCCCchhyyhhDCTTTTukuTTTkk................kdsYyysk......",
    "kCDDkkkkTchyYyyhDDTTTTTTTukuTTkkk.............kdsYyysk......",
    "kCDDk.kTTchyysyhDDDDDTTTTTTTTuTTTkkkkkkkkkkkkkkkdsYyysk.....",
    "kDDDk.kTCchhyyhhDCDDDDDDTTTTukTuuTYYYYYYYYYYYYYYdsYyysk.k...",
    "kcCk.kTTMThhhhhDDDDDDDDMDDDTTTTukTsMskssssssskssdsYyyskkdk..",
    "kcCk.kTTTTTDDDDMDDDDDMDDDDMDDDTTTMukTMuMTkkkkyMssdsYyyskk...",
    "kcCkkTMTTTDCDDCDDDDDDDDDDDDDDDDDDTTTTukTMuk.kMsssdsYyyMk....",
    "kcCkkTTTTMDDYYYYYYYYYYYYYYYYYYYYYYYYYYYTTTTkksssssdsYsysk...",
    "kcCkkTTTTTDDyyyymyyyyyyyyyyyyyYYYYYYYYYYYYYYYYYYYYdsYsysk...",
    "kcCkkMTTTTDDssssMsssssMssMsMssymykyyyyyyykyyyyyykyydsYsyMk..",
    "kcDDDTThhTDDDDDhhDDDDhhDDDDhhDdnddddddddddddddndndddMYsyMdk.",
    "kCcDDThchhMDDDhchhDDhchhDDhchhDDhchhDDchDDhDTkkkkkkkdsYsysk.",
    ".kDcDThhhhDDMDhhhhDDhhhhDDhhhhDDhhhhDDchDDhDTk......kdsYsysk",
    ".kDDkThhhhTTTMhhDhMThhDhMThhDhTThhMhTThhhhDDTk......kdsYsmsk",
    "..kkkTThhTTTTTThhTTTThhTTTThhMTTThhTTTThDDDMMk.......knccccs",
    "....kTTTkTTkMTkTTkTMkMTkTMkMMkTTkTTkMTkTTkMMTk........kCCCCy",
    "....kTMuTTuTTuTTMTTuTTuTTMTTuMTuTMuTMMMMuMMTTk........kDDDkk",
    "....kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk............",
  ],
};

// ---- dirt_pile: Loose dirt heap with a lit crest, clods, pebbles; partial ink outline on the shade side only. ----
SPR16.dirt_pile = {
  w: 24, h: 16,
  anchor: [0, 16],
  pal: VEH_B_PAL,
  rows: [
    "........................",
    "........................",
    ".........pp.............",
    "........pppppk..........",
    ".......ppmmplpkk........",
    "......pplmmmmlplk.......",
    "......plmmmMmmlllk......",
    ".....plmRmmmpmmMllk.....",
    "....ppmmmrmmmmmMMll.....",
    "....pllmmmmmmmmMMMlk....",
    "...plmmMmmmmmmnMMMMlk...",
    "..ppmmmmmmmmmmmMMMMllk..",
    ".pplmmmmmMmmmmmMrEMMllk.",
    ".plmMmmmmmmmmmmMMMMnMlk.",
    ".lmmmmmmmmmmmmmMMMMnnMlk",
    "MMMnnnnnnnnnnnnnnnnnnnMm",
  ],
};

